dist: focal

language: minimal

stages:
  - lint
  - test
  - deploy

if: branch = master OR type = pull_request

before_install:
  - tmpdaemon=$(mktemp)
  - sudo jq '."registry-mirrors" += ["https://mirror.gcr.io"]' /etc/docker/daemon.json > "$tmpdaemon"
  - sudo mv "$tmpdaemon" /etc/docker/daemon.json
  - sudo systemctl daemon-reload
  - sudo systemctl restart docker
  - docker system info

jobs:
  include:
    - stage: lint
      name: Project Syntax Verification
      script: make docker/run target=lint
    - stage: test
      name: Apply Terraform test configs in mockstack
      install:
        - make docker-compose/install
        - make mockstack/up
      script: make mockstack/pytest
      after_script:
        - make mockstack/clean
    - stage: deploy
      if: branch = master AND type = push AND repo = plus3it/terraform-aws-tardigrade-iam-principals
      before_script:
        - |
          PRIOR_VERSION=$(git describe --abbrev=0 --tags)
          RELEASE_VERSION=$(grep current_version $TRAVIS_BUILD_DIR/.bumpversion.cfg | sed 's/^.*= //' )
          RELEASE_BODY="* [terraform-aws-tardigrade-iam-principals v$RELEASE_VERSION CHANGELOG](https://github.com/plus3it/terraform-aws-tardigrade-iam-principals/blob/$RELEASE_VERSION/CHANGELOG.md)"
          export PRIOR_VERSION RELEASE_VERSION RELEASE_BODY
      script: skip
      before_deploy:
        - |
          (set -x; git tag -a $RELEASE_VERSION -m $RELEASE_VERSION)
      deploy:
        provider: releases
        api_key:
          secure: r/dLDythsLLePrjep6nUvkfjcFNcCXPbOFz5JKiNDDNEp+6SRNnvEGkyEHAsqxwzuaHbaIAZFokHbACx0+3w+n3meQHpjYUbmX8lT4bC/JhRalHd+1vdRNvavpLluNww1VYZ1vWqHE0N6S9ZBp/9vWvhiDhkpb9rFS3IMcKSx7LVf+EAI0wlYMM6WPOxONOymPl39IMrGpvzVjnj5Adxf92tyDJTIbvo/2su7us6VwhqhVUe87x2I1q/vZK7b+nLYLGI3W06G324NrE/YJCFLEXr4vvTLWzVtmFEQr1ONR+CIpQBbA3xFxMqvvugbP+4S5JgWsz9ZQUz7aVN6C4lqoQDcr6bghM2o9JdDBKTJUWmqbQ6u/vxAfUJYPPt9LRghP1w7EEPO8R9QXU/Lv5mttLShuEU7DGs6gqEGRMxwOqcBB73wgHhfqYXppnGL6cBoiC6jvoxe0bdclMq7Gxi5g7oJOQx3W1sxSvt9eJnPcOWstohez0iytQbrpSQ/NyuxLmIhizd4bVP3uxstMpPnWv/uDRib7ccZZP7plSykON9/1dJyM/jk0k9/qVvwGOyVUeEflPxDhu2eGrOmJWjVMG84xFpMfM4gKaTXVsbAAKKD+xXHSOIA4sYXiQ04Uy2Om4hOhASoJStlB7kUUVVR7gueiYc7yUKQMPSodhLlGg=
        name: $RELEASE_VERSION
        body: $RELEASE_BODY
        tag_name: $RELEASE_VERSION
        target_commitish: $TRAVIS_COMMIT
        draft: false
        on:
          branch: master
          repo: plus3it/terraform-aws-tardigrade-iam-principals
          condition: '"$PRIOR_VERSION" != "$RELEASE_VERSION"'
