version: 1

update_configs:

  - package_manager: "terraform"
    directory: "/modules/roles"
    update_schedule: "daily"

  - package_manager: "terraform"
    directory: "/modules/users"
    update_schedule: "daily"

  - package_manager: "terraform"
    directory: "/tests/create_users"
    update_schedule: "daily"

  - package_manager: "terraform"
    directory: "/tests/create_roles"
    update_schedule: "daily"

  - package_manager: "terraform"
    directory: "/tests/no_create_roles"
    update_schedule: "daily"

  - package_manager: "terraform"
    directory: "/tests/no_create_users"
    update_schedule: "daily"

  - package_manager: "go:modules"
    directory: "/tests"
    update_schedule: "daily"

  - package_manager: "python"
    directory: "/"
    update_schedule: "live"
