version: 1

update_configs:

  - package_manager: "terraform"
    directory: "/modules/roles"
    update_schedule: "daily"

  - package_manager: "terraform"
    directory: "/modules/users"
    update_schedule: "daily"
